#!/usr/bin/env python3
"""cookie_jar.py - Netscape cookie jar 解析与转换工具（蒸馏自 staging 脚本的共性问题）。

背景: skills_staging 中 scan_main.py / ssrf_net_scan.py / ssrf_net_scan2.py /
ssrf_path_brute.py / ssrf_probe.py 各自复制粘贴了一份 Netscape 格式 cookie jar 解析
逻辑(处理 #HttpOnly_ 前缀、tab 分隔字段), 但实现互有差异(有的要求恰好 7 列、
有的漏掉 secure 列、都不做过期/域名/路径过滤), 且都硬编码 /tmp/ck.txt。
本工具把该能力参数化为通用 CLI: 读 jar -> 按域名/路径/名称/过期过滤 ->
输出多种格式(Cookie 头值 / 完整头 / requests 兼容 JSON / 规范化 jar 再导出)。

用法:
  # 提取可用的 Cookie 头值(自动剔除过期, 供 curl -b / requests / ffuf -b 使用)
  python3 pentools/custom/cookie_jar.py /tmp/ck.txt
  # 只看 example.com 域(含子域)的会话 cookie, 输出完整 Cookie 头
  python3 pentools/custom/cookie_jar.py /tmp/ck.txt --domain example.com --name session --format header
  # 输出 requests 兼容 JSON(每个 cookie 一个对象)
  python3 pentools/custom/cookie_jar.py /tmp/ck.txt --format json
  # 本地自检(不依赖网络)
  python3 pentools/custom/cookie_jar.py --selftest

格式说明: 每行字段 domain [tab] include_subdomains [tab] path [tab] secure [tab]
expires(epoch) [tab] name [tab] value; #HttpOnly_ 前缀的域名行表示 HttpOnly cookie;
expires=0 视为会话 cookie(有效); 兼容无 secure 列的 6 列写法。
仅用 Python 标准库。
"""
import argparse
import json
import os
import sys
import tempfile
import time


def parse_jar(path):
    """解析 Netscape 格式 cookie jar, 返回 cookie dict 列表(含 _line 行号)."""
    try:
        f = open(path, "r", encoding="utf-8", errors="replace")
    except OSError as e:
        raise SystemExit(f"[!] 无法读取 cookie jar {path}: {e}")
    cookies = []
    with f:
        for lineno, line in enumerate(f, 1):
            line = line.rstrip("\r\n")
            if not line:
                continue
            httponly = False
            if line.startswith("#HttpOnly_"):
                httponly = True
                line = line[len("#HttpOnly_"):]
            elif line.startswith("#"):
                continue  # 纯注释行
            parts = line.split("\t")
            # 标准 7 列; 兼容无 secure 列的 6 列写法
            if len(parts) == 7:
                domain, sub, path, secure, expires, name, value = parts
            elif len(parts) == 6:
                domain, sub, path, expires, name, value = parts
                secure = "FALSE"
            else:
                continue
            try:
                expires = int(expires)
            except ValueError:
                expires = 0
            cookies.append({
                "domain": domain,
                "include_subdomains": sub.strip().upper() == "TRUE",
                "path": path,
                "secure": secure.strip().upper() == "TRUE",
                "expires": expires,
                "name": name,
                "value": value,
                "httponly": httponly,
                "_line": lineno,
            })
    return cookies


def is_expired(c, now=None):
    """expires==0 视为会话 cookie(有效); 其它早于当前时间为过期."""
    if c["expires"] == 0:
        return False
    return c["expires"] < (now if now is not None else int(time.time()))


def domain_matches(cdomain, filt):
    """cookie 域名(去前导点)是否属于 filter 域(含其子域)."""
    cd = cdomain.lstrip(".").lower()
    fd = filt.lstrip(".").lower()
    return cd == fd or cd.endswith("." + fd)


def path_matches(cpath, req_path):
    """cookie Path 是否覆盖请求路径 req_path(按 cookie 路径前缀语义)."""
    if cpath == "/":
        return True
    return req_path == cpath or req_path.startswith(cpath.rstrip("/") + "/")


def filter_cookies(cookies, domain=None, name=None, path=None,
                   include_expired=False, now=None):
    out = []
    for c in cookies:
        if not include_expired and is_expired(c, now):
            continue
        if domain and not domain_matches(c["domain"], domain):
            continue
        if name and c["name"] not in name:
            continue
        if path and not path_matches(c["path"], path):
            continue
        out.append(c)
    return out


def to_header_value(cookies):
    """输出 'name=value; name2=value2' 形式, 可直接用于 curl -b / requests / ffuf -b."""
    return "; ".join(f"{c['name']}={c['value']}" for c in cookies)


def to_jar_lines(cookies):
    """规范化 Netscape 格式再导出(保留 #HttpOnly_ 前缀)."""
    lines = ["# Netscape HTTP Cookie File",
             "# generated by pentools/custom/cookie_jar.py"]
    for c in cookies:
        dom = c["domain"]
        if c["httponly"]:
            dom = "#HttpOnly_" + dom
        sub = "TRUE" if c["include_subdomains"] else "FALSE"
        sec = "TRUE" if c["secure"] else "FALSE"
        lines.append("\t".join([dom, sub, c["path"], sec, str(c["expires"]),
                                c["name"], c["value"]]))
    return lines


def to_json(cookies):
    clean = [{k: v for k, v in c.items() if not k.startswith("_")} for c in cookies]
    return json.dumps(clean, indent=2, ensure_ascii=False)


def _selftest():
    ok = True

    def check(cond, msg):
        nonlocal ok
        if not cond:
            ok = False
            print(f"  [FAIL] {msg}")
        else:
            print(f"  [ok]   {msg}")

    jar_content = """# Netscape HTTP Cookie File
# 纯注释行应被忽略
.example.com\tTRUE\t/\tFALSE\t0\tsession\tabc123
#HttpOnly_.example.com\tTRUE\t/\tFALSE\t9999999999\tauth\ttok%3D1
other.org\tTRUE\t/\tFALSE\t0\tother\tval
expired.example.com\tTRUE\t/\tFALSE\t1\told\ttomb
sub.example.com\tFALSE\t/admin\tFALSE\t0\tsub_only\tyes
sixcol.example.com\tTRUE\t/\t0\tnosec\tv6
"""
    with tempfile.TemporaryDirectory() as td:
        jar = os.path.join(td, "ck.txt")
        with open(jar, "w") as f:
            f.write(jar_content)

        cookies = parse_jar(jar)
        check(len(cookies) == 6,
              f"解析出 6 个 cookie(含 6 列兼容行), 实际 {len(cookies)}")

        now = 2000000000  # 未来时间: 9999999999 未过期, 1 已过期
        kept = filter_cookies(cookies, now=now)
        names = {c["name"] for c in kept}
        check("old" not in names, "过期 cookie 默认被剔除")
        check({"session", "auth", "other", "sub_only", "nosec"} <= names,
              "会话/HttpOnly/子域/6列 cookie 均保留")

        hdr = to_header_value(kept)
        check("session=abc123" in hdr and "auth=tok%3D1" in hdr,
              "header value 含 session 与 auth")
        check("old=tomb" not in hdr, "header value 不含过期 cookie")

        dom = filter_cookies(cookies, domain="example.com", now=now)
        dnames = {c["name"] for c in dom}
        check("other" not in dnames and {"session", "auth", "sub_only", "nosec"} <= dnames,
              "--domain example.com 命中 example.com 及子域, 排除 other.org")

        pth = filter_cookies(cookies, path="/admin/list", now=now)
        pnames = {c["name"] for c in pth}
        check("sub_only" in pnames and "session" in pnames,
              "path 过滤: /admin 覆盖 /admin/list, / 覆盖一切")

        only = filter_cookies(cookies, name=["session"], now=now)
        check(len(only) == 1 and only[0]["name"] == "session",
              "--name session 仅保留该 cookie")

        out_jar = os.path.join(td, "out.txt")
        with open(out_jar, "w") as f:
            f.write("\n".join(to_jar_lines(kept)) + "\n")
        again = parse_jar(out_jar)
        a = {(c["domain"], c["name"], c["value"]) for c in again}
        b = {(c["domain"], c["name"], c["value"]) for c in kept}
        check(a == b, "jar 再导出-再解析 往返一致")

        js = json.loads(to_json(kept))
        check(isinstance(js, list) and js and js[0]["name"] == "session",
              "json 输出可被 json.loads 解析")

    if ok:
        print("selftest OK")
        return 0
    print("selftest FAILED")
    return 1


def main():
    ap = argparse.ArgumentParser(
        description="Netscape cookie jar 解析与转换: 读 jar -> 过滤 -> 输出多种格式")
    ap.add_argument("jar", nargs="?", help="Netscape 格式 cookie jar 文件路径")
    ap.add_argument("--domain", help="仅保留该域(含其子域)的 cookie")
    ap.add_argument("--name", action="append", default=[],
                    help="仅保留指定名称的 cookie(可多次指定)")
    ap.add_argument("--path", default=None,
                    help="仅保留能覆盖该请求路径的 cookie(如 /admin/list)")
    ap.add_argument("--include-expired", action="store_true",
                    help="包含已过期 cookie(默认剔除)")
    ap.add_argument("--format", choices=["value", "header", "json", "jar"],
                    default="value",
                    help="value=Cookie 头值(默认, 供 curl -b/requests/ffuf -b); "
                         "header=完整 'Cookie: ...' 头; json=requests 兼容数组; "
                         "jar=规范化 Netscape 再导出")
    ap.add_argument("--selftest", action="store_true",
                    help="本地自检(不依赖网络)")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(_selftest())
    if not args.jar:
        ap.error("缺少 jar 文件路径(或使用 --selftest)")

    cookies = filter_cookies(parse_jar(args.jar),
                             domain=args.domain,
                             name=args.name or None,
                             path=args.path,
                             include_expired=args.include_expired)
    if not cookies:
        print("(no cookies matched)", file=sys.stderr)
        sys.exit(0)
    if args.format == "value":
        print(to_header_value(cookies))
    elif args.format == "header":
        print("Cookie: " + to_header_value(cookies))
    elif args.format == "json":
        print(to_json(cookies))
    else:
        print("\n".join(to_jar_lines(cookies)))


if __name__ == "__main__":
    main()
